if(EXISTS "/Users/shahryar/Programming/cmu-db-course/bustub/build_rel/test/page_guard_test[1]_tests.cmake")
  include("/Users/shahryar/Programming/cmu-db-course/bustub/build_rel/test/page_guard_test[1]_tests.cmake")
else()
  add_test(page_guard_test_NOT_BUILT page_guard_test_NOT_BUILT)
endif()
